name: Daily Report

on:
  schedule:
    - cron: '0 3 * * *'  # 매일 자정 UTC → 오후 6시 MDT
  workflow_dispatch:

jobs:
  run-daily-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas matplotlib numpy requests beautifulsoup4 selenium openai schedule googletrans==4.0.0-rc1

      - name: Run daily report script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python3 daily_report.py
