
name: Daily Combined Reports

on:
  schedule:
    - cron: '0 11 * * *'   # 매일 오전 11시 UTC 실행 (한국 20시, 캘거리 05시)
  workflow_dispatch:        # 수동 실행 가능

jobs:
  daily-stock-report:
    name: 📊 Daily Stock Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas matplotlib numpy requests beautifulsoup4 selenium openai schedule googletrans==4.0.0-rc1

      - name: Run daily stock report
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          python daily_report.py

  daily-etf-report:
    name: 📈 Daily ETF & Crypto ETF Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Run ETF Recommendation Report
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          python daily_reco_report_with_etf.py
