name: Daily Report

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 UTC → 오후 6시 MDT
  workflow_dispatch:

jobs:
  run-daily-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas matplotlib numpy requests beautifulsoup4 selenium googletrans==4.0.0-rc1 openai schedule googletrans

      - name: Run daily report script
        run: python3 daily_report.py
