name: Daily Portfolio Report

on:
  schedule:
    - cron: '0 15 * * *'   # 매일 15:00 UTC (캐나다 앨버타 여름 09:00 / 겨울 08:00)
  workflow_dispatch: {}     # 수동 실행도 가능

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google credentials (from Secrets)
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > service_account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/service_account.json" >> $GITHUB_ENV

      - name: Run report
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          python portfolio_gsheet_policy_report.py

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-report-${{ github.run_id }}
          path: portfolio_gsheet_policy_report_*.html
