# ------------------------------------------------------------
# GitHub Actions workflow file (save as .github/workflows/portfolio_report.yml)
# ------------------------------------------------------------
# This workflow runs the report every day and can also be run on-demand.
# Cron is in UTC: 15:00 UTC ≈ 09:00 in Alberta (summer), 08:00 (winter).

"""
name: Daily Portfolio Report

on:
  schedule:
    - cron: '0 15 * * *'  # 15:00 UTC daily
  workflow_dispatch: {}

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client yfinance pandas numpy matplotlib requests openai

      - name: Write Google credentials (from Secrets)
        if: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON != '' }}
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > service_account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/service_account.json" >> $GITHUB_ENV

      - name: Run report
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          python portfolio_gsheet_policy_report.py

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-report-${{ github.run_id }}
          path: |
            portfolio_gsheet_policy_report_*.html
"""
